### PR TITLE
fix: use importing guide in @types/express

### PR DESCRIPTION
**Pull request by matt-sungwook**
Fixes https://github.com/nodekit-org/express-isomorphic/issues/4

### CODE REVIEW

**Comment by eldeni** [comment]
there's something I want to make sure. Even though tsconfigs are different in modules, the code that a source project should look at is the compiled version of each library. Could you explain how the error occurred? @matt-sungwook 

By the way, great initial contribution

**Comment by matt-sungwook** [comment]
Its definition mapping file also has the same way of importing as the original source.

Both `/src/createExpress.ts` and `/lib/createExpress.d.ts` have this:
`import express from 'express'`

**Comment by eldeni** [comment]
@matt-sungwook I see. But how come did the tsc check the grammatical integrity of library codes? code of dependency modules should be ignored by tsc in the original source

**Comment by matt-sungwook** [comment]
I agree that it's weird, and I'll check our project. However, I think it's still better to use `import * as ~ from 'express'` because the exported namespace `e` is like `export const e = {}`.

**Comment by eldeni** [comment]
issue solved (or found not an error). closing for housekeeping purpose

**Pull request closed without merging**
